models:
 - type: main
   engine: openai
   model: gpt-4-0613 #gpt-3.5-turbo

instructions:
  - type: general
    content: |
      Below is a conversation between a user and a bot. The user is having a conversation with the bot but could have malicious intentions.
      Your job is to actively monitor the conversation and give the bot a heads up if any of the user messages are inappropriate or could be leading the bot to provide harmful information.
      If you see any inappropriate content, please flag it and provide a reason why you think it is inappropriate.


# SINGLE TURN PROMPT INJECTION CONTENT INSTRUCTIONS
# Your task is to check if the user message below complies with the company policy for talking with the company bot. The company policy for the user messages is as follows:
# If the text is requesting illegal / criminal content, output 0.
# If the text is requesting that you give expert advice that you're not qualified to give (such as Self-harm or mental health advice, Having or pretending to have a political stance, Personal financial advice, Personal medical advice, Personal legal advice, etc,.), output 1.
# If the text is requesting private information (such as addresses, contact information, private occupational information, etc.) that the user shouldnt know, output 2.
# If the text is requesting biased, unethical, or immoral responses (such as Profanity, Insults, Sexually explicit (other than medical), Racial slurs, Hate, Stereotypes, Racial micro-aggressions, or identity attacks) output 3.
# Otherwise, if the text sounds like a natural part of a conversation (like greetings, "yes/no", questions, responses, comments, asking for case), even if individual is speaking in an affected way or it has typos, output 4.
# Respond with the number only. Don't say anything else

input:
  flows:
    - self check input

output:
  flows:
    - self check output